### ISSUE TITLE
more trees read than in the newick file ?

### ISSUE THREAD

**Issue by lcottret** [chaoszhang/A-pro#9] opened 2020-10-15 13:11 UTC
Hi,

I'm testing Astral-pro which looks very nice ! I have a newick file with 49 trees with 1469 species and a file with gene-species correspondances. I launched it in a cluster with XmX=521G but it ended with a java heap space problem:
Calculating distance matrix (for completion of X) ....with 4 distance matrices in parallel
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at phylonet.coalescent.SimilarityMatrix.populateByQuartetDistance(SimilarityMatrix.java:104)
        at phylonet.coalescent.SimilarityMatrix.populate(SimilarityMatrix.java:258)
        at phylonet.coalescent.WQDataCollection.calculateDistances(WQDataCollection.java:851)
        at phylonet.coalescent.WQDataCollection.formSetX(WQDataCollection.java:613)
        at phylonet.coalescent.AbstractInference.setupSearchSpace(AbstractInference.java:319)
        at phylonet.coalescent.AbstractInference.setup(AbstractInference.java:299)
        at phylonet.coalescent.CommandLine.runOnOneInput(CommandLine.java:623)
        at phylonet.coalescent.CommandLine.runInference(CommandLine.java:614)
        at phylonet.coalescent.CommandLine.main(CommandLine.java:535)

However, at the beginning of the log, it's written that 882 trees have been read:
The number of input tree read is 49
882 trees read from outfiles/49ogs/49ogsAllTrees.tree
49 extra trees.

Is this the problem ?

I tested with a newick file with 2 lines corresponding to 2 trees,  and this time 36 trees have been read...
This is the file I attached. Is there a problem with the format ?

Note that the problem occurs with and without file associating gene ids and species ids.

Regards,

[testTrees.txt](https://github.com/chaoszhang/A-pro/files/5385053/testTrees.txt)

**Comment by lcottret** [comment] 2020-10-15 15:59
Note that even with the example1.tre file (10 trees inside) in example directory, the log output is 
The number of input tree read is 10
165 trees read from example1.tre
29 extra trees.

I think I miss something...

**Comment by chaoszhang** [comment] 2020-10-15 18:16
Hi,
The input trees are multi-copy trees and the "input trees read" are single-copy trees generated from multi-copy trees. A-pro consumes a lot of memory when the number of taxa is high. The problem is fixed in the C++ version (see astral-pro in https://github.com/chaoszhang/ASTER). You may try the C++ version if you wish. Let me know, if it is difficult to install/run.
Best,
Chao

**Comment by lcottret** [comment] 2020-10-16 14:57
Hi, 
It worked very well with the C++ version, thank you !
Ludo

**Comment by chaoszhang** [comment] 2020-10-17 13:54
You are welcome.

**Closed by chaoszhang** 2020-10-17 13:54 UTC
